language: python
sudo: required
services:
    - mysql
    - docker
python:
    - "3.5"
env:
    - TEST_DIR=models
before_install:
    - mkdir -p ~/cs4501/db
    - docker run --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v ~/cs4501/db:/var/lib/mysql  mysql:5.7.14
    - sleep 10
    - docker ps -a
    - docker run -it --name mysql-cmdline --link mysql:db mysql:5.7.14 bash -c "mysql -uroot -p '$3cureUS' -h db; create user 'www'@'%' identified by '$3cureUS'; create database cs4501 character set utf8; grant all on cs4501.* to 'www'@'%'; ^D"
script:
    - bin/start
    - cd $TEST_DIR && python manage.py test
