language: python
sudo: required
services:
    - mysql
    - docker
python:
    - "3.5"
before_install:
    - mkdir -p ~/cs4501/db
    - docker run --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v ~/cs4501/db:/var/lib/mysql  mysql:5.7.14
    - sleep 10
script:
    - bin/start
    - docker start app_web_1
    - docker start app_models_1
    - docker start app_exp_1
    - docker exec app_web_1 python manage.py test
    - docker exec app_models_1 python manage.py test
    - docker exec app_exp_1 python manage.py test
