models:
   image: djangorest
   external_links:
      - mysql:db
   ports:
      - "8001:8000"
   volumes:
      - ./models:/app
   stdin_open: true
   command: bash -c "python manage.py collectstatic --noinput > /dev/null && python manage.py makemigrations models_app && python manage.py migrate && python manage.py loaddata db.json && mod_wsgi-express start-server --working-directory . --url-alias /static build/static --reload-on-changes --log-to-terminal models/wsgi.py"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

exp:
   image: djangorest
   links:
      - models:models-api
      - kafka:kafka-api
   ports:
      - "8002:8000"
   volumes:
      - ./exp:/app
   stdin_open: true
   command: "mod_wsgi-express start-server --working-directory . --reload-on-changes --log-to-terminal exp/wsgi.py"

web:
   image: djangorest
   links:
      - exp:exp-api
   ports:
      - "8000:8000"
   volumes:
      - ./web:/app
   stdin_open: true
   command: bash -c "python manage.py collectstatic --noinput > /dev/null && mod_wsgi-express start-server --working-directory . --document-root build --reload-on-changes --log-to-terminal web/wsgi.py"

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   volumes:
      - ./batch:/app
   links:
      - kafka:kafka
      - es:es
   command: "python search.py"
